---
author: Davood Roshan
date: "2022-09-07T19:36:26+02:00"
summary: The 3rd Young-ISA meeting is dedicated to Collaborative Workflow in Data Science.
type: postevent
tags:
- post
title: 3rd Young-ISA Meeting
---

**Date:** Friday October 7th, 2022 <br>
**Location:** Room AD2-010, Bernal Institute, University of Limerick <br>
**Time:** 10.00 - 16.30 <br>


The **Young Statisticians' Section of the <a href="https://istat.ie/" target="_blank">Irish Statistical Association**</a> (Young-ISA) was formed in 2019 with the objectives of creating and cultivating a network of career-young statisticians across Ireland, supporting their professional development and providing a link to the Irish Statistical Association.</p>

This event is the 3rd Young-ISA meeting that will bring together many career-young statisticians in Ireland to focus on collaborative workflow in Statistics and Data Science, using tools such as Github to carry out projects within teams. We will host **two keynote talks and a round table** featuring Dr Isabella Gollini (UCD) and Dr Fernando de Pol Mayer (MU), as well as **short research talks** delivered by career-young researchers from different Irish universities, distributed over two presentation rounds.

**The winners of the Young-ISA Twitter Poster Conference will be announced at this event.** Please check [here](/events/posts/2022-10-05-poster-conference-2022/) for more detail on how to participate. 

### Invited Speakers

[Dr. Isabella Gollini](https://people.ucd.ie/isabella.gollini), Assistant Professor in Statistics, University College Dublin. <br>
[Dr. Fernando de Pol Mayer](http://leg.ufpr.br/~fernandomayer/), Researcher and Lecturer in Statistics, Maynooth University. <br>

### Programme

Please check later for the full program.


### Registration
The event is **free to attend for ISA members**. If you attended CASI in 2022 you are already an ISA member. If you are not yet a member, click [here](https://istat.ie/n2020/join-isa/) (membership is free for students).

There is **no charge** for attending this event. To register please use the Eventbrite link [here](https://www.eventbrite.ie/e/3rd-young-isa-event-collaborative-workflow-in-data-science-tickets-414540029387?aff=ebdssbdestsearch).

<br>
<br>

Category: [<u>Events</u>](/events/)