---
author: Davood Roshan
date: "2023-09-19T19:36:26+02:00"
summary: "The 4th Young-ISA meeting is dedicated to Researcher's Toolkit - Publication, Progression, and People."
type: preevent
tags:
- post
title: 4th Young-ISA Meeting
---

**Date:** Friday November 17th, 2023 <br>
**Location:** LCI-G0189, [Institute for Lifecourse and Society (ILAS)](https://maps.app.goo.gl/UGbrNg1EFggGUqJs6), University of Galway (H91 C7DK) <br>
**Time:** 9.30 - 18.00 <br>
**Theme of the event:** Researchers’ Toolkit: Publication, Progression, and People <br>

The **Young Statisticians' Section of the <a href="https://istat.ie/" target="_blank">Irish Statistical Association**</a> (Young-ISA) was formed in 2019 with the objectives of creating and cultivating a network of career-young statisticians across Ireland, supporting their professional development and providing a link to the Irish Statistical Association.</p>

This event is the 4th Young-ISA meeting that will bring together many career-young statisticians in Ireland to focus on **Researchers’ Toolkit: Publication, Progression, and People**. This event offers early career researchers and Ph.D. students an excellent opportunity to gain insights into advancing their careers in academia. We will host **three keynote talks** where keynote speakers will share their perspectives on crucial aspects of this journey. In particular, they will discuss the significance of publication quantity versus quality, initiating collaborations, writing grants, how to progress in academia, and other relevant topics. 

There will be also a series of short research talks delivered by career-young researchers from different Irish universities, distributed over two presentation rounds. In addition, a round table will be delivered with our keynote speakers to further discuss the theme of the event. 

The event also dedicates one of its afternoon session to a joint event organised by Young-ISA and The [British  and Irish Region (BIR) of the International Biometric Society (IBS)](https://bir.biometricsociety.org/home), featuring two talks by early-career researchers from both Young-ISA ad BIR.  


**The winners of our next Young-ISA Twitter Poster Conference (stay tuned) will be announced at this event.** Please check [here](/events/posts/2023-17-11-poster-conference-2023/) for more detail on how to participate. 

### Invited Speakers

[Brendan Murphy](https://people.ucd.ie/brendan.murphy), School of Mathematics & Statistics, University College Dublin. <br>

[Kathleen O'Sullivan](http://research.ucc.ie/profiles/D019/kathleenosullivan), School of Mathematical Sciences, University College Cork. <br>

[Carl Scarrott](https://www.universityofgalway.ie/our-research/people/mathematical-statistical-sciences/carlscarrott/), School of Mathematical and Statistical Sciences, University of Galway. <br>

### Programme

**The full program is available [here](/events/posts/4th_Y-ISA_meeting_abstracts.pdf).**


### Registration
The event is **free to attend for ISA members**. If you attended CASI in 2023 you are already an ISA member. If you are not yet a member, click [here](https://istat.ie/n2020/join-isa/) (membership is free for students).

To register for the event please use the Eventbrite link [here](https://www.eventbrite.ie/e/4th-young-isa-meeting-tickets-722097050717?aff=oddtdtcreator).



<br>
<br>
<br>

Category: [<u>Events</u>](/events/)