---
author: Gabriel Palma
date: "2023-09-19T19:36:26+02:00"
summary: "The Young ISA Mentorship Programme."
type: postevent
tags:
- post
title: The Young ISA Mentorship Programme
---

**Date:** January 17th, 2024 <br>
**Theme of the event:** The Young ISA Mentorship Programme <br>

The **Young ISA Mentorship Programme** was launched in **January 2024** on International Mentoring Day (17th of January). The aim of this programme is to match members of the young ISA with other ISA members in later stages of their career to exchange experience, knowledge, expertise and career advice. The initiative aims to enhance connections across the field of statistics and across Ireland as well as encouraging and supporting engagement between career stages.
If you would be interested in joining this initiative as either a mentor of mentee in 2024. Please fill in the registration form below by **23:59 on the 26th of January**.

### Registration form

**The full program is available [here](https://forms.office.com/e/kJ67dfP8y6).**


### FAQs

* 1. **Can I be a mentor and mentee?** Yes. You can register as a mentor, mentee or both. You can choose from all three options in the registration form.

* 2. **Can I be a mentor if I am a PhD student?** Yes. We encourage any final year PhD students who wish to be mentors to register.
* 3. **How long does the programme last?** The programme will begin in February 2024 and end in December 2024. However, mentors and mentees can decide to keep up the connection after this if they wish.
* 4. **Can I get more than one mentor/mentee?** No. One mentor will be assigned one mentee and vice versa.

* 5. **What is the time commitment?** There is no specific time commitment. A mentor must arrange a meeting (virtual or in-person) with the mentee within one week of assignment and the meeting should take place with the month of March 2024. After the initial meeting it is up to the mentee to make contact with the mentor and arrange meetings which suit both parties. We would recommend one 30-minute meeting per month.

* 6. **Can I opt-out after being assigned a mentor/mentee?** Yes. After being assigned a mentor/mentee you can opt-out of the programme. However, we would request you do so as soon as possible to allow for the mentor/mentee to be reassigned.

* 7. **Will I definitely be assigned a mentor/mentee if I register for the programme?** No. Unfortunately we cannot guarantee that everyone will be assigned a mentor/mentee as there may not be an equal number of both. Mentors/mentees will be assigned based on a matching process and we will endeavour to match those best suited to each other and match as many mentor/mentee pairs as possible from those who apply.



<br>
<br>
<br>

Category: [<u>Events</u>](/events/)