---
author: Gabriel Palma
date: "2024-09-19T19:36:26+02:00"
summary: "The 5th Young-ISA meeting is dedicated to Transferable Skills: Insights from Academia and Industry."
type: postevent
tags:
- post
title: 5th Young-ISA Meeting
---

**Date:** Monday December 9th, 2024 <br>
**Location:** [UCD O'Brien Centre for Science](https://maps.app.goo.gl/5tHkKHTLYWoRCDEx6), University College Dublin (UCD) <br>
**Time:** 9 am - 5 pm GMT <br>
**Theme of the event:** Transferable Skills: Insights from Academia and Industry <br>

The **Young Statisticians' Section of the <a href="https://istat.ie/" target="_blank">Irish Statistical Association**</a> (Young-ISA) was formed in 2019 with the objectives of creating and cultivating a network of career-young statisticians across Ireland, supporting their professional development and providing a link to the Irish Statistical Association.</p>

This event is the 5th Young-ISA meeting that will bring together many career-young statisticians in Ireland to focus on **Transferable Skills: Insights from Academia and Industry**. This event offers early career researchers and PhD students an excellent opportunity to gain insights into advancing their careers in academia. We will host **three keynote talks** where keynote speakers will share their perspectives on crucial aspects of this journey.

There will also be a series of short research talks delivered by career-young researchers from different Irish universities, as well as a round table discussion with our keynote speakers on the theme of the event, with the opportunity for audience questions.

The event also dedicates one of its afternoon session to a joint event organised by Young-ISA and The [British  and Irish Region (BIR) of the International Biometric Society (IBS)](https://bir.biometricsociety.org/home), featuring two talks by early-career researchers from both Young-ISA ad BIR.  

**The winners of our next Young-ISA Twitter Poster Conference (stay tuned) will be announced at this event.** Please check [here](https://docs.google.com/forms/d/e/1FAIpQLSef3Lh_q-JzQReItGDUazGadZ1vJBEYPn8Z9zbTlmLo0RPE-A/viewform) for more detail on how to participate. 

### Invited Speakers

[Nial Friel](https://people.ucd.ie/nial.friel), School of Mathematics & Statistics, University College Dublin. <br>

[Órlaith Burke](https://www.linkedin.com/in/orlaith-burke/), Global Innovation Director, Accenture. <br>

Owen McGrath, Department of Mathematics and Statistics, University of Limerick. <br>

### Programme

**The full program will be available soon.**


### Registration
The event is **free to attend for ISA members**. If you attended CASI in 2024 you are already an ISA member. If you are not yet a member, click [here](https://istat.ie/n2020/join-isa/) (membership is free for students).

To register for the event please use the Eventbrite link [here](https://www.eventbrite.ie/e/5th-young-isa-meeting-tickets-1077334098289?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl).



<br>
<br>
<br>

Category: [<u>Events</u>](/events/)