---
author: Davood Roshan
date: "2019-10-04T18:36:26+02:00"
summary: This is inaugural event...
tags:
- post
title: Inaugural Young-ISA Meeting
---
**Date:** Friday October 4, 2019 <br>
**Location:** Glenroyal Hotel, Maynooth <br>
**Time:** 10.00 - 19.00 <br>

**The full program is available [here](inaug_meeting_program_full.pdf).**

---


The **Young Statisticians' Section of the <a href="https://istat.ie/" target="_blank">Irish Statistical Association**</a> (Young-ISA) was formed in 2019 with the objectives of creating and cultivating a network of career-young statisticians across Ireland, supporting their professional development and providing a link to the Irish Statistical Association.</p>

This inaugural event will gather together early career statisticians from across Ireland for a series of talks on career development in academia and industry. Keynote talks will be given by established professionals in both fields with the remainder of the two sessions devoted to showcasing some of the research projects conducted in universities across Ireland by postgraduate and post-doctoral researchers.

**Invited Speakers:**<br>
Dr. Norma Bargary, Lecturer in Statistics, University of Limerick. <br>
Dr. Aidan Boland, Senior Data Scientist, Edge by Ascential. <br>

<p><strong>Programme</strong><br>
<table class="tg">
  <tr>
    <td class="tg-s7xz">10:00 - 10:30</td>
    <td class="tg-oedl">Registration</td>
  </tr>
  <tr>
    <td class="tg-zv4m">10:30 - 10:50</td>
    <td class="tg-zv4m">Welcome Address</td>
  </tr>
  <tr>
    <td class="tg-zv4m">10:50 - 11:40</td>
    <td class="tg-zv4m">Dr. Norma Bargary - "Statisticians in Academia"</td>
  </tr>
  <tr>
    <td class="tg-zv4m">11:40 - 12:00</td>
    <td class="tg-zv4m">Coffee Break</td>
  </tr>
  <tr>
    <td class="tg-zv4m">12:00 - 13:00</td>
    <td class="tg-zv4m">Research Presentations - Round 1</td>
  </tr>
  <tr>
    <td class="tg-zv4m">13:00 - 14:00</td>
    <td class="tg-zv4m">Lunch</td>
  </tr>
  <tr>
    <td class="tg-zv4m">14:00 - 14:50</td>
    <td class="tg-zv4m">Dr. Aidan Boland - "Statisticians in Industry"</td>
  </tr>
  <tr>
    <td class="tg-zv4m">14.50 - 15.20</td>
    <td class="tg-zv4m">Round Table - Dr. Norma Bargary and Dr. Aidan Boland</td>
  </tr>
  <tr>
    <td class="tg-zv4m">15:20 - 15:50</td>
    <td class="tg-zv4m">Coffee Break</td>
  </tr>
  <tr>
    <td class="tg-zv4m">15:50 - 16:50</td>
    <td class="tg-zv4m">Research Presentations - Round 2</td>
  </tr>
  <tr>
    <td class="tg-zv4m">16:50 - 19:00</td>
    <td class="tg-zv4m">Wine Reception and Closing Address</td>
  </tr>
</table>

The event is open to all early career statisticians (including postgraduate and PhD students, postdoctoral researchers and lecturers) and all ISA members.

There is **no charge** for attending this event. To register please use the Eventbrite <a href="https://www.eventbrite.ie/e/inaugural-young-isa-meeting-tickets-72058373535" target="_blank"><strong>link</strong></a> by Friday, 27 September.

<br>
<br>

Category: [<u>Events</u>](/events/)