---
date: "2020-05-21"
title: News
---
## <u>**_The 5th Young-ISA meeting is dedicated to Transferable Skills: Insights from Academia and Industry._**</u>

**Date:** Monday December 9th, 2024 <br>
**Location:** [University College Dublin (UCD)](https://maps.app.goo.gl/RpZzSyuJsEftA6i68) <br>
**Time:** 9:00 - 17.00 <br>
**Theme of the event:** Transferable Skills: Insights from Academia and Industry <br>

The **Young Statisticians' Section of the <a href="https://istat.ie/" target="_blank">Irish Statistical Association**</a> (Young-ISA) was formed in 2019 with the objectives of creating and cultivating a network of career-young statisticians across Ireland, supporting their professional development and providing a link to the Irish Statistical Association.</p>

This event is the 5th Young-ISA meeting that will bring together many career-young statisticians in Ireland to focus on **Transferable Skills: Insights from Academia and Industry**. This event offers early career researchers and PhD students an excellent opportunity to gain insights into advancing their careers in academia. We will host **three keynote talks** where keynote speakers will share their perspectives on crucial aspects of this journey. 

There will also be a series of short research talks delivered by career-young researchers from different Irish universities, as well as a round table discussion with our keynote speakers on the theme of the event, with the opportunity for audience questions.

The event also dedicates one of its afternoon sessions to a joint event organised by Young-ISA and The [British  and Irish Region (BIR) of the International Biometric Society (IBS)](https://bir.biometricsociety.org/home), featuring talks by early-career researchers from both Young-ISA and BIR.

### Poster Session
We are also delighted to announce that this year we will have a poster session at the event. We invite you to sign up  [here](https://docs.google.com/forms/d/e/1FAIpQLSef3Lh_q-JzQReItGDUazGadZ1vJBEYPn8Z9zbTlmLo0RPE-A/viewform) to indicate if you would like to present a poster on the day.

### Invited Speakers

[Nial Friel](https://people.ucd.ie/nial.friel), School of Mathematics & Statistics, University College Dublin. <br>

[Órlaith Burke](https://www.accenture.com/ie-en), Global Life Sciences Innovation Director, Accenture. <br>

[Owen McGrath](https://www.ul.ie/macsi/), Department of Mathematics and Statistics, University of Limerick. <br>

--- 

## <u>**_The 4th Young-ISA meeting is dedicated to Researcher's Toolkit - Publication, Progression, and People._**</u>

**Date:** Friday November 17th, 2023 <br>
**Location:** LCI-G0189, [Institute for Lifecourse and Society (ILAS)](https://maps.app.goo.gl/UGbrNg1EFggGUqJs6), University of Galway (H91 C7DK) <br>
**Time:** 9.30 - 18.00 <br>
**Theme of the event:** Researchers’ Toolkit: Publication, Progression, and People <br>

The **Young Statisticians' Section of the <a href="https://istat.ie/" target="_blank">Irish Statistical Association**</a> (Young-ISA) was formed in 2019 with the objectives of creating and cultivating a network of career-young statisticians across Ireland, supporting their professional development and providing a link to the Irish Statistical Association.</p>

This event is the 4th Young-ISA meeting that will bring together many career-young statisticians in Ireland to focus on **Researchers’ Toolkit: Publication, Progression, and People**. This event offers early career researchers and Ph.D. students an excellent opportunity to gain insights into advancing their careers in academia. We will host **three keynote talks** where keynote speakers will share their perspectives on crucial aspects of this journey. In particular, they will discuss the significance of publication quantity versus quality, initiating collaborations, writing grants, how to progress in academia, and other relevant topics. 

There will be also a series of short research talks delivered by career-young researchers from different Irish universities, distributed over two presentation rounds. In addition, a round table will be delivered with our keynote speakers to further discuss the theme of the event. 

The event also dedicates one of its afternoon session to a joint event organised by Young-ISA and The [British  and Irish Region (BIR) of the International Biometric Society (IBS)](https://bir.biometricsociety.org/home), featuring two talks by early-career researchers from both Young-ISA ad BIR.  


**The winners of our next Young-ISA Twitter Poster Conference (stay tuned) will be announced at this event.** Please check [here](/events/posts/2023-17-11-poster-conference-2023/) for more detail on how to participate. 

### Invited Speakers

[Brendan Murphy](https://people.ucd.ie/brendan.murphy), School of Mathematics & Statistics, University College Dublin. <br>

[Kathleen O'Sullivan](http://research.ucc.ie/profiles/D019/kathleenosullivan), School of Mathematical Sciences, University College Cork. <br>

[Carl Scarrott](https://www.universityofgalway.ie/our-research/people/mathematical-statistical-sciences/carlscarrott/), School of Mathematical and Statistical Sciences, University of Galway. <br>

--- 

## <u>**_Call for expressions of interest – Young-ISA are currently seeking new members_**</u>

The Young Statisticians’ Section of the ISA is inviting expressions of interest from early career statisticians (first 10 years of their careers – including students) based in Ireland.

The Young-ISA committee was formed in 2019, and is dedicated to the creation and promotion of a network of career-young statisticians in Ireland, supporting their professional development, organizing events and activities, and providing an interface with ISA.

We host several events annually, including webinars, workshops, in-person meetings, and competitions. Visit our [webpage](https://young-istat.github.io/events/) for details and see our remit [here](https://young-istat.github.io/about/Y-ISA_remit.pdf).

We're searching for individuals with fresh ideas to help us organize exciting events for the early-career stats community. If you're interested, send us an email at **young.istat@gmail.com** with the subject line _*"Young-ISA Committee 2023"*_ by **5 pm on Sunday 30 April**. Make sure to include a short statement (up to 250 words) about yourself and why you're thrilled to join the team. You'll be expected to attend monthly committee meetings, but don't worry - we'll make them lively and engaging!

Please note that to take up a position you must be a [member of the ISA](https://istat.ie/n2020/join-isa/). The annual fee is €20 for regular membership but is FREE for students or those who attend our annual [Conference on Applied Statistics Ireland (CASI)](https://casi.ie/).

The names of the 2023-25 Young-ISA committee will be announced at the Young-ISA AGM during CASI 2023.



## <u>**_Young-ISA online workshop on Statistics in Medicine_**</u>
<p style="font-size:15px">Updated on 2023-02-13</p>

Our **Young-ISA online workshop on Statistics in Medicine** is an event that has emerged from our [monthly webinar series](/webinars) and aims to bring together many career-young statisticians in Ireland to focus on **application of statistics in medicine**. We will have **one keynote speaker**, [Prof. John Newell](https://www.universityofgalway.ie/our-research/people/mathematics-statistics-and-applied-mathematics/johnnewell/) and **two invited speakers** delivered by [Koyel Majumdar](https://www.linkedin.com/in/koyel-majumdar-0b261b154/?originalSubdomain=ie) (UCD) and [Dr. Arthur White](https://www.tcd.ie/research/profiles/?profile=arwhite) (TCD) who are going to discuss the application of their research works in medical science. For more information about this event please visit [here](/events/posts/2023-03-10-webinar_statsmedicine/).

For registration please visit [here](https://www.eventbrite.ie/e/y-isa-online-workshop-on-statistics-in-medicine-tickets-545951665127).

---


## <u>**_3rd Young-ISA Meeting_**</u>
<p style="font-size:15px">Updated on 2022-09-07</p>
This event is the 3rd Young-ISA meeting that will gather together early career statisticians from across Ireland for a series of talks dedicated to collaborative workflow in Statistics and Data Science, using tools such as Github to carry out projects within teams. Keynote talks will be given by established professionals in both fields with the remainder of the two sessions devoted to showcasing some of the research projects conducted in universities across Ireland by postgraduate and post-doctoral researchers. Read more [here](/events/posts/2022-10-07-meeting3/). 

For registration please visit [here](https://www.eventbrite.ie/e/3rd-young-isa-event-collaborative-workflow-in-data-science-tickets-414540029387?aff=ebdssbdestsearch).

---

## <u>**_Young-ISA 3rd Twitter Poster Conference (#YISAPoster2022)_**</u>
<p style="font-size:15px">Updated on 2022-09-07</p>

The 3rd **#YISAPoster2022** Twitter Conference will be held entirely online over [Twitter](https://twitter.com/Young_Stats_ISA) on October 5th 2022 and aims to provide an opportunity for Statistician and Data Scientist around the world to meet online, share thier research and engage in scientific debate. For more information on how to join the **#YISAPoster2022** event please visit [here](/events/posts/2022-10-05-poster-conference-2022/). 


---

## <u>**_Webinar Series: Evaluation of credit risk measures using structural models_**</u>
<p style="font-size:15px">Updated on 2022-04-03</p>

Dr. Zahra Eskandari from Central Tehran Branch, Islamic Azad University, Tehran, Iran will speak about the estimation methods of economic capital where has been recently become an appropriate capital to cover unexpected losses in financial institutions, especially banks. Accurate estimation of economic capital is therefore essential to protect banks against the risks. For more information about this webinar please visit [here](/webinars/posts/2022-04-12-webinar13/). 


---

## <u>**_Webinar Series: Pattern Based prediction, a new machine learning method for detecting population outbreaks_**</u>
<p style="font-size:15px">Updated on 2022-03-02</p>

Gabriel Rodrigues Palma from Hamilton Institute, Maynooth University will speak about a new machine learning method called Pattern-Based Prediction (PBP) for predicting insect outbreaks based on a time series of aphids, pests species of cereal crops. For more information about this webinar please visit [here](/webinars/posts/2022-03-10-webinar12/). 

---


## <u>**_Webinar Series: Stochastic invasion of variants of concern and effectiveness of border controls in a population with heterogeneous immunity_**</u>
<p style="font-size:15px">Updated on 2022-01-27</p>

[Jacob Curran-Sebastian](https://twitter.com/CurranSebastian) from University of Manchester will speak on the use of a multi-type branching process model to understand the stochastic invasion of SARS-CoV-2 variants of concern into a country where a vaccination program is ongoing and where part of the population exhibits immunity due to prior infection with a resident strain. For more information about this webinar please visit [here](/webinars/posts/2022-02-10-webinar11/). 

---

## <u>**_Young-ISA Christmas quiz_**</u>
<p style="font-size:15px">Updated on 2021-12-18</p>

The Young-ISA is delighted to invite everyone to take part in our Christmas quiz [here](https://forms.gle/Ma3Bn8H3EArcDmPU7)!

The deadline for answers is 12 pm on 24th December 2021. Happy Christmas!

---

## <u>**_2nd Young-ISA Meeting_**</u>
<p style="font-size:15px">Updated on 2021-12-18</p>
This event is the 2nd Young-ISA meeting that will gather together early career statisticians from across Ireland for a series of talks dedicated to Communication and Reproducibility in Statistics. Keynote talks will be given by established professionals in both fields with the remainder of the two sessions devoted to showcasing some of the research projects conducted in universities across Ireland by postgraduate and post-doctoral researchers. Read more [here](/events/posts/2022-01-28-meeting2/). 

For registration please visit [here](https://www.eventbrite.ie/e/2nd-young-isa-meeting-tickets-229761511867).

---

## <u>**_Webinar Series: On the privilege of turning our world into data_**</u>
<p style="font-size:15px">Updated on 2021-11-01</p>

Dr Rohan Alexander from University of Toronto will speak on the origins of Data Science, and especially the contributions of Irish statisticians on the field. For more information about this webinar please visit [here](/webinars/posts/2021-12-16-webinar10/). 


---

## <u>**_Webinar Series: Estimating energy allocation between somatic and gonadic growth_**</u>
<p style="font-size:15px">Updated on 2021-11-01</p>

[Dr Hideyasu Shimadzu](https://www.lboro.ac.uk/departments/maths/staff/hideyasu-shimadzu/) from Loughborough University, UK will speak on the nature of the challenges associated with quantifying the growth patterns and energy allocation strategies of living organisms and the interactions with broader biological communities in which they reside. For more information about this webinar please visit [here](/webinars/posts/2021-11-12-webinar9/). 

For registration please visit [here](https://www.eventbrite.ie/e/y-isa-webinar-series-energy-allocation-between-somatic-and-gonadic-growth-tickets-203112684507).

---

## <u>**_Webinar Series: Assessing the impact of deprivation and ethnicity on COVID burden in England_**</u>
<p style="font-size:15px">Updated on 2021-09-26</p>

[Dr. Tullia Padellini](https://tulliapadellini.github.io/) from Department of Epidemiology and Biostatistics, School of Public Health, Imperial College London will speak on how the ethnically diverse and deprived communities have been differentially affected by the COVID-19 pandemic in the UK by assessing three different metrics of COVID-19 burden (test positivity, prevalence and vaccination rates). For more information about this webinar please visit [here](/webinars/posts/2021-10-14-webinar8/). 

For registration please visit [here](https://www.eventbrite.ie/e/y-isa-webinar-series-the-impact-of-deprivation-and-ethnicity-on-covid-tickets-179481081747).


---


## <u>**_Webinar Series: Characterisation of the probability and information entropy of a process with an increasing sample space of different functional forms, with applications to (1) the Broad Money Supply and (2) Hyperinflation_**</u>
<p style="font-size:15px">Updated on 2021-09-01</p>

Laurence Francis Lacey, Director of Lacey Solutions Ltd, will speak on the application of different functional forms of the expansion of the sample space with time in expansion of the broad money supply of US$ over the period 2001 to 2019. For more information about this webinar please visit [here](/webinars/posts/2021-09-16-webinar7/). 

For registration please visit [here](https://www.eventbrite.ie/e/y-isa-webinar-series-characterisation-of-information-entropy-of-a-process-tickets-169393419277).

---

## <u>**_Webinar Series: Condition based maintenance - a guideline for choosing between repair and replacement_**</u>
<p style="font-size:15px">Updated on 2021-03-15</p>

Dr. Elham Mosayebi Omshi from the Department of Mathematics, Statistics and Computer Science, Allameh Tabataba'i University will speak on an adapted maintenance modeling framework for modeling the maintenance cost of a system. For more information about this webinar please visit [here](/webinars/posts/2021-04-15-webinar6/). 

For registration please visit [here](https://www.eventbrite.ie/e/y-isa-webinar-series-guideline-of-choosing-between-repair-and-replacement-tickets-146486931355).

---

## <u>**_Webinar Series: Efficient Conversion Probability Estimator for Display Advertising_**</u>
<p style="font-size:15px">Updated on 2021-01-28</p>

[Dr. Abdollah Safari](https://pharmsci.ubc.ca/directory/abdollah-safari#:~:text=Abdollah%20is%20a%20statistician%20at,in%20every%20application%20of%20statistics.&text=Safari%20received%20his%20PhD%20in,analysis%20on%20Big%20Data%20problems.) from faculty of Pharmaceutical Sciences, University of British Colombia will speak on methods to estimate the conversion probability of an advertisement to quantify the value of an ad. For more information about this webinar please visit [here](/webinars/posts/2021-03-11-webinar5/). 

For registration please visit [here](https://www.eventbrite.ie/e/138800214177).

---

## <u>**_Webinar Series: Introductory data science, a fresh look_**</u>
<p style="font-size:15px">Updated on 2021-01-28</p>

[Dr. Mine Çetinkaya-Rundel](http://www2.stat.duke.edu/~mc301/) from the School of Mathematics, University of Edinburgh; Department of Statistical Science, Duke University; and RStudio will speak on a fresh approach to teaching data science at the introductory level and will introduce the design philosophy behind the curriculum as well as provide directions in assessment in this online teaching era. For more information about this webinar please visit [here](/webinars/posts/2021-02-11-webinar4/). 

For registration please visit [here](https://www.eventbrite.ie/e/138791776941).

---


## <u>**_Webinar Series: An introduction to the tidymodels package_**</u>
<p style="font-size:15px">Updated on 2021-01-08</p>

[Bruna Wundervald](https://brunaw.com/) from the School of Mathematics, National University of Ireland, Maynooth will introduce tidymodels packages, and how they can be used for the pre-processing of data, and training and validation of machine learning models. For more information about this webinar please visit [here](/webinars/posts/2021-01-21-webinar3/). 

For registration please visit [here](https://www.eventbrite.ie/e/135974925663).

---

## <u>**_Webinar Series: Confirmed Speakers for the New Year_**</u>
<p style="font-size:15px">Updated on 2020-12-15</p>

Our confirmed speakers for the January, February and March 2021 Young ISA webinar series are as follows:

- 2021-01-28: **Bruna Wundervald** from School of Mathematics, National University of Ireland, Maynooth.

- 2021-02-11: **Dr. Mine Çetinkaya-Rundel** from the School of Mathematics, University of Edinburgh and RStudio.

- 2021-02-11: **Dr. Abdollah Safari** from faculty of Pharmaceutical Sciences, University of British Colombia

For more information about these webinars please click [here](/webinars/). 

---

## <u>**_Webinar Series: Clustering Big Data with Mixed Features_**</u>
<p style="font-size:15px">Updated on 2020-12-02</p>

Joshua Tobin from the School of Computer Science & Statistics, Trinity College Dublin, will introduce a new clustering method for large mixed attribute datasets which adapts and extends the popular peak-finding technique. The algorithm presented is competent at deciding the correct number of clusters and executes with subquadratic complexity. For more information about this webinar please click [here](/webinars/posts/2020-12-10-webinar2/). 

For registration please click [here](https://www.eventbrite.ie/e/y-isa-webinar-series-clustering-big-data-with-mixed-features-tickets-131319198257).

---



## <u>**_Webinar Series: Global Short-Term Forecasting of Covid-19 Cases_**</u>
<p style="font-size:15px">Updated on 2020-10-29</p>

[Dr. Thiago de Paula Oliveira](https://prof-thiagooliveira.netlify.com/) from the Roslin Institute, University of Edinburgh will speak on a new modelling framework of COVID-19 to forecast the number of cases, study the effects of covariates (such as lockdown policies), and generate forecasts for smaller regions within countries and up to six days ahead. For more information about this webinar please click [here](/webinars/posts/2020-11-12-webinar1/). 

For registration please click [here](https://www.eventbrite.ie/e/y-isa-webinar-series-global-short-term-forecasting-of-covid-19-cases-tickets-127039764355).

---


## <u>**_Twitter Poster Conference (#YISAPoster2020)_**</u>
<p style="font-size:15px">Updated on 2020-05-21</p>

The **#YISAPoster2020** Twitter Conference will be held entirely online over [Twitter](https://twitter.com/Young_Stats_ISA) and aims to provide an opportunity for Statistician and Data Scientist around the world to meet online, share thier research and engage in scientific debate. For more information on how to join the **#YISAPoster2020** event please visit [here](/events/2020-07-15-poster-conference-2020/). 

---

## <u>**_Inaugural Young-ISA Meeting_**</u>
<p style="font-size:15px">Updated on 2019-09-01</p>
This inaugural event will gather together early career statisticians from across Ireland for a series of talks on career development in academia and industry. Keynote talks will be given by established professionals in both fields with the remainder of the two sessions devoted to showcasing some of the research projects conducted in universities across Ireland by postgraduate and post-doctoral researchers.

**Invited Speakers:**<br>
Dr. Norma Bargary, Lecturer in Statistics, University of Limerick. <br>
Dr. Aidan Boland, Senior Data Scientist, Edge by Ascential. <br>

The event is **free of charge** to attend and is open to all early career statisticians (including postgraduate and PhD students, postdoctoral researchers and lecturers) and all ISA members. 

Read more [here](/events/2019-09-01-inaugural-meeting/). 

