---
author: Davood Roshan
date: "2020-11-12T18:36:26+02:00"
summary: Dr. Thiago de Paula Oliveira from the Roslin Institute, University of Edinburgh will speak on a new modelling framework of COVID-19 to forecast the number of cases, study the effects of covariates (such as lockdown policies), and generate forecasts for smaller regions within countries and up to six days ahead.
type: preweb
tags:
- post
title: Global Short-Term Forecasting of Covid-19 Cases
---
**Date:** Thursday November 12th, 2020 <br>
**Location:** Zoom (the link will be posted soon) <br>
**Time:** 12.00pm WET <br>


### Speaker
[Dr. Thiago de Paula Oliveira](https://prof-thiagooliveira.netlify.com/) from Roslin Institute, University of Edinburgh


### Abstract
The continuously growing number of COVID-19 cases pressures healthcare services worldwide. Accurate short-term forecasting is thus vital to support country-level policy making. The strategies adopted by countries to combat the pandemic vary, generating different uncertainty levels about the actual number of cases. Accounting for the hierarchical structure of the data and accommodating extra-variability is therefore fundamental. We introduce a new modelling framework to describe the course of the pandemic with great accuracy, and provide short-term daily forecasts for every country in the world. We show that our model generates highly accurate forecasts up to six days ahead, and use estimated model components to cluster countries based on recent events. We introduce statistical novelty in terms of modelling the autoregressive parameter as a function of time, increasing predictive power and flexibility to adapt to each country. Our model can also be used to forecast the number of cases, study the effects of covariates (such as lockdown policies), and generate forecasts for smaller regions within countries. Consequently, it has strong implications for global planning and decision making. We constantly update forecasts and make all results freely available to any country in the world through an online Shiny dashboard.

### Supplementary Materials
**Paper:** [https://arxiv.org/abs/2006.00111](https://arxiv.org/abs/2006.0011)

### Registration
- **Registration** is free and open to everyone. 
- Please click [here](https://www.eventbrite.ie/e/y-isa-webinar-series-global-short-term-forecasting-of-covid-19-cases-tickets-127039764355) to register. 


### Webinar Video

<iframe width="560" height="315" src="https://www.youtube.com/embed/q8eXc0Gpcc4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Category: [<u>Webinars</u>](/webinars/)