---
author: Davood Roshan
date: "2020-12-10T18:36:26+02:00"
summary: Joshua Tobin from the School of Computer Science & Statistics, Trinity College Dublin, will introduce a new clustering method for large mixed attribute datasets which adapts and extends the popular peak-finding technique. The algorithm presented is competent at deciding the correct number of clusters and executes with subquadratic complexity. 
type: preweb
tags:
- post
title: Clustering Big Data with Mixed Features
---
**Date:** Thursday December 10th, 2020 <br>
**Location:** Zoom (the link will be posted soon) <br>
**Time:** 12.00pm WET <br>


### Speaker
Joshua Tobin from School of Computer Science & Statistics, Trinity College Dublin


### Abstract
Clustering large, mixed data is a central problem in data mining. Many approaches adopt the idea of k-means, and hence are sensitive to initialisation, detect only spherical clusters, and require a priori the unknown number of clusters. We develop a new clustering algorithm for large data of mixed type, aiming at improving the applicability and efficiency of the peak-finding technique. The improvements are threefold: (1) the new algorithm is applicable to mixed data; (2) the algorithm is capable of detecting outliers and clusters of relatively lower density values; (3) the algorithm is competent at deciding the correct number of clusters. The computational complexity of the algorithm is greatly reduced by applying a fast k-nearest neighbours method and by scaling down to component sets. We present experimental results to verify that our algorithm works well in practice.

### Supplementary Materials
**Paper:** The paper is available on Arxiv [here](https://arxiv.org/abs/2011.06043)

**Codes:** The associated Python library, CPFcluster, is available [here](https://pypi.org/project/CPFcluster/). 


### Registration
- **Registration** is free and open to everyone. 
- Please click [here](https://www.eventbrite.ie/e/y-isa-webinar-series-clustering-big-data-with-mixed-features-tickets-131319198257) to register. 
- Further details on this webinar will be posted in the coming days.

### Webinar Video

<iframe width="560" height="315" src="https://www.youtube.com/embed/1nicOA5vZWs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



Category: [<u>Webinars</u>](/webinars/)