---
author: Davood Roshan
date: "2021-04-15T18:36:26+02:00"
summary: Dr. Elham Mosayebi Omshi will speak on an adapted maintenance modeling framework for modeling the maintenance cost of a system.
type: postweb
tags:
- post
title: Condition based maintenance - a guideline for choosing between repair and replacement

---
**Date:** Thursday April 15th, 2021 <br>
**Location:** Zoom (the link will be posted soon) <br>
**Time:** 12.00pm WET <br>


### Speaker
Dr. Elham Mosayebi Omshi from Allameh Tabataba'i University.


### Abstract

Maintenance is referred to actions done for preserving or restoring a system to its functioning mode. Repair and replacement are crucial ones. The former is usually imperfect, while the latter is perfect but more expensive. As the objective is minimizing the maintenance cost, a tradeoff between repairs and replacements is needed. Here, we focus on imperfect maintenance efficiency and propose an adapted maintenance modeling framework under an aperiodic inspection and maintenance scheme. Inverse Gaussian process is considered for degradation modeling, and a random improvement factor model describes the effect of imperfect repair actions on the degradation level. To characterize the randomness in the effect of imperfect repair, we assume that the random improvement factor follows a beta distribution. The balance between imperfect repairs and preventive replacement is made by introducing a new decision variable. With this definition, classical maintenance policies can be obtained for specific values of decision variables. The closed-form of the cost function is assessed based on semi-regenerative properties. Numerical experiments show the flexibility of the proposed maintenance modeling framework and its ability to adapt to imperfect efficiency levels.

### Registration
- **Registration** is free and open to everyone. 
- Please click [here](https://www.eventbrite.ie/e/138800214177) to register.



Category: [<u>Webinars</u>](/webinars/)