---
author: Davood Roshan
date: "2021-12-16T18:36:26+02:00"
summary: Dr Rohan Alexander from University of Toronto will speak on the origins of Data Science, and especially the contributions of Irish statisticians on the field.
type: preweb
tags:
- post
title: On the privilege of turning our world into data
---
**Date:** Thursday December 16th, 2021 <br>
**Time:** 2.00pm WET <br>

### Join the Webinar

  - **Webinar** is free and open to everyone. 
  - Click [here](/webinars/posts/webinar10_calendar.ics) to download the calendar invite to the meeting. . 
  - Or, alternatively, the **link** to the webinar is: https://us02web.zoom.us/j/86960753282?pwd=QTJhQ1RabkdVckJKMnBzMGFZWWdVQT09 <br>


### Speaker
Dr Rohan Alexander from University of Toronto


### Abstract
I will begin by discussing the origins of data science, especially mentioning the contributions of Irish statisticians. I will turn to what I see data science as, and what I see are some of our roles and responsibilities as quantitatively interested folks. I will then go through various applications including: understanding the effect of elections; hate speech detection; and the reproducibility of COVID-19 pre-prints. While going those applications I will focus more on what I learned and how I developed, rather than specific results. I will close with a series of open questions.


Category: [<u>Webinars</u>](/webinars/)
