---
author: Davood Roshan
date: "2021-10-14T18:36:26+02:00"
summary: Dr. Tullia Padellini from Department of Epidemiology and Biostatistics, School of Public Health, Imperial College London will speak on how the ethnically diverse and deprived communities have been differentially affected by the COVID-19 pandemic in the UK by assessing three different metrics of COVID-19 burden (test positivity, prevalence and vaccination rates).
type: postweb
tags:
- post
title: Assessing the impact of deprivation and ethnicity on COVID burden in England
---
**Date:** Thursday October 14th, 2021 <br>
**Location:** Zoom (the link will be posted soon) <br>
**Time:** 12.00pm WET <br>


### Speaker
[Dr. Tullia Padellini](https://tulliapadellini.github.io/) from Department of Epidemiology and Biostatistics, School of Public Health, Imperial College London


### Abstract

There is extensive evidence to suggest that ethnically diverse and deprived communities have been differentially affected by the COVID-19 pandemic in the UK. We investigate the impact of such inequalities by assessing the effect of area level deprivation and ethnicity on three different metrics of COVID-19 burden (test positivity, prevalence and vaccination rates), which, together, provide a comprehensive picture of the status of the pandemic. We define a hierarchical logistic model to evaluate the separate and combined effects of the two community-level characteristics and how those effects have changed over the course of the pandemic, accounting for residual confounding by means of spatio-temporally structured random effects.Through its spatio-temporal components, the model can also be used to highlight areas which are both
transiently and persistently different than the national average in the outcome levels, making our proposal useful for surveillance as well as policy purposes.

We analyse outcomes as weekly counts at the Lower Tier Local Authority (LTLA) level in the time period from June 2020 to August 2021. We find evidence that areas characterised by social deprivation and high proportion of non-white ethnicity have higher susceptibility to COVID-19 as well as reduced resilience at community level through lower vaccination rates. The impact of the two covariates on test positivity and prevalence varies over time: deprivation has a stronger effect until October-November 2020; thereafter, the effect of ethnicity becomes more pronounced. The results can be used to inform relevant policies aimed at mitigating the effect of social inequalities in COVID burden.


### Registration
- **Registration** is free and open to everyone. 
- Please click [here](https://www.eventbrite.ie/e/y-isa-webinar-series-the-impact-of-deprivation-and-ethnicity-on-covid-tickets-179481081747) to register.

Category: [<u>Webinars</u>](/webinars/)
