---
author: Davood Roshan
date: "2021-11-12T18:36:26+02:00"
summary: Dr Hideyasu Shimadzu from Loughborough University, UK, will speak on the nature of the challenges associated with quantifying the growth patterns and energy allocation strategies of living organisms and the interactions with broader biological communities in which they reside.
type: preweb
tags:
- post
title: Estimating energy allocation between somatic and gonadic growth
---
**Date:** Friday November 12th, 2021 <br>
**Time:** 12.00pm WET <br>
**Link to join the webinar:** https://us02web.zoom.us/j/84752172292?pwd=RFUvUkFPeFcvSllyUTYwMDkxT0VTQT09 <br>


### Speaker
[Dr Hideyasu Shimadzu](https://www.lboro.ac.uk/departments/maths/staff/hideyasu-shimadzu/) from Loughborough University, UK.


### Abstract
Quantifying the growth patterns and energy allocation strategies of livings is essential to comprehend the biological characteristics of organisms and the interactions with broader biological communities in which they reside. Mathematical models, like allometric energy-based growth models, play a pivotal role in delineating such body growth patterns. However, modelling approaches often face some major challenges that stem from both model nonlinearity and data limitation in practice. The talk investigates the nature of the challenges and develops a flexible growth model, illustrating applications in real data often collected in the field of biology.

### Registration
- **Registration** is free and open to everyone. 
- Please click [here](https://www.eventbrite.ie/e/y-isa-webinar-series-energy-allocation-between-somatic-and-gonadic-growth-tickets-203112684507) to register.

### Webinar Video
<iframe width="560" height="315" src="https://www.youtube.com/embed/Ht9fCZ9xxuo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


Category: [<u>Webinars</u>](/webinars/)
