---
author: Davood Roshan
date: "2021-02-11T18:36:26+02:00"
summary: Dr. Mine Çetinkaya-Rundel from the School of Mathematics, University of Edinburgh; Department of Statistical Science, Duke University; and RStudio will speak on a fresh approach to teaching data science at the introductory level and will introduce the design philosophy behind the curriculum as well as provide directions in assessment in this online teaching era.
type: postweb
tags:
- post
title: Introductory data science, a fresh look

---
**Date:** Thursday February 11th, 2021 <br>
**Location:** Zoom (the link will be posted soon) <br>
**Time:** 12.00pm WET <br>


### Speaker
[Dr. Mine Çetinkaya-Rundel](http://www2.stat.duke.edu/~mc301/) from the School of Mathematics, University of Edinburgh; Department of Statistical Science, Duke University; and RStudio.


### Abstract
Modern statistics is fundamentally a computational discipline, but too often this fact is not reflected in our statistics curricula. With the rise of data science, it has become increasingly clear that students want, expect, and need explicit training in this area of the discipline. Additionally, recent curricular guidelines clearly state that working with data requires extensive computing skills and that statistics students should be fluent in accessing, manipulating, analyzing, and modeling with professional statistical analysis software. In this talk, we will describe a fresh approach to teaching data science at the introductory level, introduce the design philosophy behind the curriculum, and give examples from course materials as well as from student projects. We will also discuss new directions in assessment and tooling as we scale up the course and move it online.

### Registration
- **Registration** is free and open to everyone. 
- Please click [here](https://www.eventbrite.ie/e/138791776941) to register.


Category: [<u>Webinars</u>](/webinars/)