---
date: "2019-03-29"
title: About
---


The **Young Statisticians' Section of the** [**Irish Statistical Association**](https://istat.ie/) (Young-ISA) aims to create and cultivate a network of career-young statisticians across Ireland, statisticians in the early stages of their careers. The ISA established the Young-ISA to support social and professional opportunities for career-young statisticians within the ISA community. 

The Young-ISA Section focuses on: 

* **Networking** -- *Create and promote a network of career-young statisticians in Ireland.* <br>
Young-ISA is a forum, for undergraduate and postgraduate students, researchers, lecturers and professionals, in all fields of Statistics, across academia, industry and other research institutions, to exchange and discuss ideas. Young-ISA provides an interface between career-young statisticians and the ISA.

* **Development** -- *Support the professional development of career-young statisticians.* <br>
In addition to promoting activities of the ISA and joint initiatives, the Young-ISA organises events, workshops and meetings. Young-ISA provides high-quality career guidance and information, and fosters a culture of interdisciplinary collaboration within its community.

* **Outreach** -- *Promote activities and prospects of a career in Statistics.* <br>
Young-ISA commits to raising awareness of the role of Statistics in modern day society. Young-ISA works with the ISA to advertise opportunities of the ISA and joint initiatives. Young-ISA shares news related to research topics, job opportunities and events of interest. 

# Join Us

Membership to the Young-ISA is open to all ISA members who consider themselves as career-young statisticians. If you wish to become a member, email us at **young.istat@gmail.com** or visit the [**ISA website**](https://istat.ie/).

